#!/bin/zsh
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# bsp, stack , float
yabai -m config layout bsp

yabai -m config window_placement second_child

# padding
yabai -m config top_padding 24
yabai -m config bottom_padding 24
yabai -m config left_padding   24
yabai -m config right_padding  24
yabai -m config window_gap 24

# mouse
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

#yabai -m config focus_follows_mouse autoraise
yabai -m config mouse_follows_focus on

# yabai -m config mouse_drop_action swap

# Disable apps
yabai -m rule --add app="^System Settings" manage=off
yabai -m rule --add app="^RiotClient" manage=off
yabai -m rule --add app="^Finder" manage=off
yabai -m rule --add app="^League of Legends" manage=off
yabai -m rule --add app="^iterm2" manage=off
yabai -m rule --add subrole="AXSystemDialog$" manage=off mouse_follows_focus=off
yabai -m rule --add title="^Picture in Picture$" manage=off mouse_follows_focus=off
yabai -m rule --add title="^Keymapp" manage=off layer=above sticky=on mouse_follows_focus=off


# window
yabai -m config window_topmost on # floating windows stay on top
yabai -m config window_border on
yabai -m config window_border_hidpi on
yabai -m config window_border_width 2
yabai -m config active_window_border_color 0xffff0000
yabai -m config window_border_blur off

yabai -m window window_animation_duration 0.2
yabai -m window window_animation_frame_rate 60

yabai -m window --toggle border

