format = """
$directory\
$git_branch\
$git_state\
$git_status\
$fill\
$python\
$nodejs\
$cmd_duration\
$time\
$line_break\
$character\
"""

[character]
success_symbol = "[󱞩](bold white)"
error_symbol = "[󱞩](bold red)"

[directory]
truncation_length = 10
truncation_symbol = "~/"
read_only = " "

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style)"
symbol = "󰘬 "
style = "purple"
[git_status]
style = "blue"
format = " [$all_status$ahead_behind]($style)"
untracked = "U"
modified = "M"
staged = "S"

[time]
disabled = false
format = "[$time]($style)"
style = "#767676"          # grey

[fill]
symbol = " "

[cmd_duration]
min_time = 100
show_milliseconds = true
format = " [$duration]($style) "
style = "#767676"                # grey

[python]
format = "[${symbol} (${pyenv_prefix})(${version})({$virtualenv})]($style) "
symbol = ' '
style = "blue bold"
pyenv_version_name = true
pyenv_prefix = 'pyenv '

[nodejs]
format = '[$symbol($version)]($style) '
